language: node_js
node_js:
  - "stable"
cache:
  directories:
    - build-suite/node_modules
before_install:
    - cd build-suite
    - npm install -g grunt-cli
install:
    - npm install
    - npm install grunt
script:
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then grunt dist --branch=$TRAVIS_PULL_REQUEST_BRANCH --build=$TRAVIS_JOB_NUMBER --password=$DW_PASSWORD --project=$PROJECT; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ];  then grunt dist --branch=master                      --build=$TRAVIS_JOB_NUMBER --password=$DW_PASSWORD --project=$PROJECT; fi'
