# Yaml Parser:  http://yaml-online-parser.appspot.com/
build:
- 'clean:build'
- 'dw_checkout'
- 'dw_npm_execute'
- 'dw_copy'
- 'dw_insert_buildinfo'
- 'sass:build'
- 'postcss:build'
- 'browserify:build'
- 'dw_optimize'
- 'dw_merge'
- 'dw_compress'
upload:
- 'dw_upload:code'
activate:
- 'dw_activate:code'
importSite:
- 'dw_prepare_site_import:default'
- 'compress:siteImport'
- 'dw_upload:siteImport'
- 'dw_import:site'
initSite:
- 'dw_prepare_site_import:init'
- 'compress:siteImport'
- 'dw_upload:siteImport'
- 'dw_import:site'
initDemoSite:
- 'dw_prepare_site_import:demo'
- 'compress:siteImport'
- 'dw_upload:siteImport'
- 'dw_import:site'
importMeta:
- 'dw_bm_login'
- 'compress:siteMeta'
- 'http:createMetaDirectory'
- 'dw_upload:siteMeta'
- 'http:unzipMeta'
- 'dw_bm_http:validateCustomMeta'
- 'dw_bm_checkprogress:customMetaValidation'
- 'dw_bm_import_meta:customMetaImport'
- 'dw_bm_checkprogress:customMetaImport'
- 'dw_bm_http:validateSystemMeta'
- 'dw_bm_checkprogress:systemMetaValidation'
- 'dw_bm_import_meta:systemMetaImport'
- 'dw_bm_checkprogress:systemMetaImport'
importContent:
- 'dw_bm_login'
- 'dw_bm_ensure_no_import:content'
- 'dw_bm_import_content'
- 'dw_bm_checkprogress:content'
exportUnits:
- 'dw_bm_login'
- 'dw_bm_export_units'
- 'dw_bm_checkprogress:exportUnits'
- 'dw_bm_download'
triggerReindex:
- 'dw_bm_login'
- 'dw_bm_reindex'
dist:
- 'build'
- 'upload'
- 'activate'
css:
- 'sass:dev'
- 'postcss:dev'
watch:
- 'css'
- 'browserify:dev'
- 'watch'
default:
- 'help'
